### ISSUE TITLE
XTBFrequencyVerifier missing method

### ISSUE THREAD

**Issue by kspieks** [xiaoruiDong/RDMC#24]
https://github.com/xiaoruiDong/RDMC/blob/ce091ca281e4899440ccf4975758ec0c886b3844/rdmc/conformer_generation/ts_verifiers.py#L17-L34

GaussianIRCVerifier has an argument for the method. XTBFrequencyVerifier should be the same
https://github.com/xiaoruiDong/RDMC/blob/ce091ca281e4899440ccf4975758ec0c886b3844/rdmc/conformer_generation/ts_verifiers.py#L120-L121

**Comment by hwpang** [comment]
I will work on this
