### ISSUE TITLE
Documentation Example Doesn't Work

### ISSUE THREAD

**Issue by JacksonBurns** [xiaoruiDong/RDMC#82]
This example of initializing an RDMCMol from a SMIELS string in the docs: https://github.com/xiaoruiDong/RDMC/blob/main/docs/source/index.rst?plain=1#L40 doesn't work, raising this error:
```
>>> m = RDKitMol('C') 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ChemEGrad2022\mambaforge\envs\fastprop310\lib\site-packages\rdmc\mol.py", line 70, in __init__
    raise ValueError(f'mol should be rdkit.Chem.rdchem.Mol / RWMol. '
ValueError: mol should be rdkit.Chem.rdchem.Mol / RWMol. Got: <class 'str'>
```

**Comment by xiaoruiDong** [comment]
> This example of initializing an RDMCMol from a SMIELS string in the docs: https://github.com/xiaoruiDong/RDMC/blob/main/docs/source/index.rst?plain=1#L40 doesn't work, raising this error:
> 
> ```
> 
> >>> m = RDKitMol('C') 
> 
> Traceback (most recent call last):
> 
>   File "<stdin>", line 1, in <module>
> 
>   File "C:\Users\ChemEGrad2022\mambaforge\envs\fastprop310\lib\site-packages\rdmc\mol.py", line 70, in __init__
> 
>     raise ValueError(f'mol should be rdkit.Chem.rdchem.Mol / RWMol. '
> 
> ValueError: mol should be rdkit.Chem.rdchem.Mol / RWMol. Got: <class 'str'>
> 
> ```

Wow. Thank you for catching this. I can't believe I kept this wrong for so long...
