### ISSUE TITLE
cached_property was only introduced from python 3.8

### ISSUE THREAD

**Issue by shihchengli** [xiaoruiDong/RDMC#87]
# Description
The `cached_property` is used in [base.py](https://github.com/xiaoruiDong/RDMC/blob/main/rdmc/external/logparser/base.py#L4), and it is implemented in the `functools` package since python 3.8 (See [here](https://docs.python.org/3/library/functools.html#functools.cached_property)). However, RDMC allows python version >=3.6.

# Bug description
When using RDMC in python 3.7 (or lower version), `ImportError: cannot import name 'cached_property' from 'functools'` would appear.

**Comment by xiaoruiDong** [comment]
@shihchengli Good catch.
I am also aware of that, but I haven't implemented it yet.

I plan to stop the support of Python 3.6 right now (as it reached end-of-life on Dec 23, 2021). Also, stop the support of Python 3.7 as its EOL is Jun 27, 2023, but will hold a little bit until RMG gets upgraded to Python 3.8+. Within 6 months, we will get to the EOL of Python 3.8, so I may also stop the support of it afterward.
